name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow for manual triggers.

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dependencies to a specific directory we can reuse
          mkdir -p lambda_package
          pip install --target lambda_package -r requirements.txt
          # Also install globally for linting/testing
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint Python Code
        run: |
          pylint src/ rss_bouncer.py --disable=C,R --fail-under=8

      - name: Create Lambda Package
        run: |
          # Copy our Lambda code maintaining the package structure
          cp rss_bouncer.py lambda_package/
          # Create src directory in lambda_package and copy contents
          mkdir -p lambda_package/src
          cp -r src/* lambda_package/src/
          # Create __init__.py if it doesn't exist
          touch lambda_package/src/__init__.py
          # Create the zip file from the package directory
          cd lambda_package
          zip -r ../infrastructure/lambda_function.zip .
          cd ..
          ls -la infrastructure/lambda_function.zip

      - name: Upload Lambda Package
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: infrastructure/lambda_function.zip
          retention-days: 1

  plan:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Lambda Package
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="raindrop_api_token_rss_to_raindrop_llm=${{ secrets.RAINDROP_API_TOKEN }}" \
            -var="openai_api_token_rss_to_raindrop_llm=${{ secrets.OPENAI_API_TOKEN }}" \
            -var="github_actions_role_arn=${{ secrets.AWS_IAM_ROLE_ARN }}"

  deploy:
    needs: [plan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Lambda Package
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Terraform Init
        run: terraform init

      - name: Check Required Secrets
        run: |
          if [ -z "${{ secrets.RAINDROP_API_TOKEN }}" ]; then
            echo "Error: RAINDROP_API_TOKEN secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.OPENAI_API_TOKEN }}" ]; then
            echo "Error: OPENAI_API_TOKEN secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_IAM_ROLE_ARN }}" ]; then
            echo "Error: AWS_IAM_ROLE_ARN secret is not set"
            exit 1
          fi

      - name: Delete Existing Resources
        run: |
          # List and detach all attached policies
          if aws iam list-attached-role-policies --role-name rss_to_raindrop_lambda_role >/dev/null 2>&1; then
            for ARN in $(aws iam list-attached-role-policies --role-name rss_to_raindrop_lambda_role --query 'AttachedPolicies[*].PolicyArn' --output text); do
              echo "Detaching policy: $ARN"
              aws iam detach-role-policy --role-name rss_to_raindrop_lambda_role --policy-arn "$ARN" || true
            done

            # List and delete all inline policies
            for POLICY in $(aws iam list-role-policies --role-name rss_to_raindrop_lambda_role --query 'PolicyNames[]' --output text); do
              echo "Deleting inline policy: $POLICY"
              aws iam delete-role-policy --role-name rss_to_raindrop_lambda_role --policy-name "$POLICY" || true
            done

            # Now delete the role
            echo "Deleting role"
            aws iam delete-role --role-name rss_to_raindrop_lambda_role || true
          else
            echo "Role rss_to_raindrop_lambda_role does not exist, skipping deletion"
          fi

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="raindrop_api_token_rss_to_raindrop_llm=${{ secrets.RAINDROP_API_TOKEN }}" \
            -var="openai_api_token_rss_to_raindrop_llm=${{ secrets.OPENAI_API_TOKEN }}" \
            -var="github_actions_role_arn=${{ secrets.AWS_IAM_ROLE_ARN }}"
