name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow for manual triggers.

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint Python Code
        run: |
          pylint src/ rss_bouncer.py --disable=C,R --fail-under=8

      - name: Create Lambda Package
        run: |
          zip -r infrastructure/lambda_function.zip src/ rss_bouncer.py requirements.txt
          ls -la infrastructure/lambda_function.zip

      - name: Upload Lambda Package
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: infrastructure/lambda_function.zip
          retention-days: 1

  plan:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Lambda Package
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Terraform Init
        run: terraform init

      - name: Import Existing Resources
        run: |
          # Import the Lambda role if it exists
          terraform import aws_iam_role.lambda_role rss_to_raindrop_lambda_role || true
          # Import the role policy attachment if it exists
          terraform import aws_iam_role_policy_attachment.lambda_basic rss_to_raindrop_lambda_role/AWSLambdaBasicExecutionRole || true

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="raindrop_test_token=${{ secrets.raindrop_test_token }}" \
            -var="openai_test_token=${{ secrets.openai_test_token }}"

  deploy:
    needs: [plan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Lambda Package
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Terraform Init
        run: terraform init

      - name: Import Existing Resources
        run: |
          # Import the Lambda role if it exists
          terraform import aws_iam_role.lambda_role rss_to_raindrop_lambda_role || true
          # Import the role policy attachment if it exists
          terraform import aws_iam_role_policy_attachment.lambda_basic rss_to_raindrop_lambda_role/AWSLambdaBasicExecutionRole || true

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="raindrop_test_token=${{ secrets.raindrop_test_token }}" \
            -var="openai_test_token=${{ secrets.openai_test_token }}"