name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow for manual triggers.

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy Infrastructure
        run: |
          aws sts get-caller-identity